### PR TITLE
Automated Velero version update 1.11.0

### PR DESCRIPTION
**Pull request by replicated-ci-kurl**
Automated changes by the [cron-velero-update](https://github.com/replicatedhq/kURL/blob/main/.github/workflows/update-velero.yaml) GitHub action

```release-note
Adds [Velero add-on](https://kurl.sh/docs/add-ons/velero) version 1.11.0.
```

### CODE REVIEW

**Comment by rrpolanco** [comment]
> https://testgrid.kurl.sh/run/pr-4638-07b56ca-velero-1.11.0-k8s-docker-2023-06-23T04:10:08Z

Flannel add-on installation is broken:
```
2023-06-23 04:26:57+00:00 ⚙  Addon flannel 0.22.0
2023-06-23 04:26:58+00:00 error: json: cannot unmarshal object into Go struct field Kustomization.patchesStrategicMerge of type patch.StrategicMerge
2023-06-23 04:26:58+00:00 An error occurred on line 143
+ KURL_EXIT_STATUS=1
```
https://testgrid.kurl.sh/run/pr-4638-07b56ca-velero-1.11.0-k8s-docker-2023-06-23T04:10:08Z?kurlLogsInstanceId=vsywqotavofnjxaf&nodeId=vsywqotavofnjxaf-initialprimary#L977

**Comment by emosbaugh** [comment]
@laverya is this due to your change here?

https://github.com/replicatedhq/kURL/pull/4632/files

can we use that syntax with old kubernetes?

**Comment by laverya** [comment]
> can we use that syntax with old kubernetes?

I dearly hope so...

**Comment by rrpolanco** [comment]
Linking story: Add post install upgrade verification to Velero tests [sc-80994](https://app.shortcut.com/replicated/story/80994/add-post-install-upgrade-verification-to-wait-for-velero-deployment-to-rollout-to-testgrid-tests)

**Review by rrpolanco — APPROVED** [review]

**Pull request merged**
