### PR TITLE
Upgrade Postgres from 10.21 to 14.4

### PR DESCRIPTION
**Pull request by sgalsaleh**
#### What type of PR is this?

type::feature

#### What this PR does / why we need it:

Upgrades Postgres from version 10.21 to 14.4

#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Upgrades the internal database (Postgres) used by the KOTS admin console four major versions, from `10.21-alpine` to `14.4-alpine`.
```

#### Does this PR require documentation?

NONE

### CODE REVIEW

**Comment by emosbaugh** [comment]
Testgrid upgrade failures look relevant

```
2022-07-22 23:27:30+00:00 deployment.apps/kurl-proxy-kotsadm configured
2022-07-22 23:31:09+00:00  [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]   [|]   [/]   [-]   [\]  '/usr/local/share/postgresql/tsearch_data/swedish.stop' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data/swedish.stop'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/tsearch_data/synonym_sample.syn' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data/synonym_sample.syn'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/tsearch_data/thesaurus_sample.ths' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data/thesaurus_sample.ths'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/tsearch_data/turkish.stop' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data/turkish.stop'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/tsearch_data/unaccent.rules' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data/unaccent.rules'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/tsearch_data/xsyn_sample.rules' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data/xsyn_sample.rules'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/tsearch_data' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/tsearch_data'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql/postgresql.conf.sample.orig' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql/postgresql.conf.sample.orig'
2022-07-22 23:31:09+00:00 '/usr/local/share/postgresql' -> '/var/lib/postgresql/upgrade/pg10/share/postgresql'
2022-07-22 23:31:09+00:00 '/usr/local/share' -> '/var/lib/postgresql/upgrade/pg10/share'
2022-07-22 23:31:09+00:00 2022-07-22 23:30:57.210 UTC [59] LOG:  shutting down
2022-07-22 23:31:09+00:00 2022-07-22 23:30:57.227 UTC [10] LOG:  database system is shut down
2022-07-22 23:31:09+00:00 waiting for server to shut down.... done
2022-07-22 23:31:09+00:00 server stopped
2022-07-22 23:31:09+00:00 Running in verbose mode
2022-07-22 23:31:09+00:00 "/var/lib/postgresql/upgrade/pg10/bin/pg_ctl" -w -l "pg_upgrade_server.log" -D "/var/lib/postgresql/data/pgdata" -o "-p 50432 -c autovacuum=off -c autovacuum_freeze_max_age=2000000000  -c listen_addresses='' -c unix_socket_permissions=0700" start >> "pg_upgrade_server.log" 2>&1
2022-07-22 23:31:09+00:00 
2022-07-22 23:31:09+00:00 There seems to be a postmaster servicing the old cluster.
2022-07-22 23:31:09+00:00 Please shutdown that postmaster and try again.
2022-07-22 23:31:09+00:00 Failure, exiting
```

**Review by emosbaugh — CHANGES_REQUESTED** [review]
See my comment [here](https://github.com/replicatedhq/kURL/pull/3168#issuecomment-1194468412)

**Comment by sgalsaleh** [comment]
@emosbaugh yeah that's what i see locally as well, was just validating that testgrid shows the same thing. pr is not ready for review yet, i only marked it ready to trigger the tests (not sure if that's required). moving back to a draft.

**Comment by emosbaugh** [comment]
tests will run without marking it to ready

Sent via Superhuman ***@***.***>

**Review by divolgin — APPROVED** [review]

**Review by emosbaugh — APPROVED** [review]

**Pull request merged**
