### PR TITLE
Revert "Automated Prometheus version update 0.48.0-16.1.0"

### PR DESCRIPTION
**Pull request by laverya**
Reverts replicatedhq/kURL#1650

Unfortunately, there are a few issues with this (possibly with the upstream chart, possibly with how we're using it)

1. Antiaffinity for the prometheus-k8s statefulset was broken due to changing labels (`app: prometheus` has been replaced by `app.kubernetes.io/name: prometheus`)
```
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: prometheus
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: k8s
        app.kubernetes.io/managed-by: prometheus-operator
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/version: 2.27.1
        operator.prometheus.io/name: k8s
        operator.prometheus.io/shard: "0"
        prometheus: k8s
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prometheus
              - key: prometheus
                operator: In
                values:
                - k8s
            topologyKey: kubernetes.io/hostname
```
2. At least one service has been broken by the same thing

### CODE REVIEW

**Comment by laverya** [comment]
There's an open PR for the service breakage: https://github.com/prometheus-community/helm-charts/pull/1010

**Review by emosbaugh — APPROVED** [review]

**Comment by keithlayne** [comment]
@laverya Just saw this, looks like a couple lines need to change. I totally missed this in my PR, feel like I should throw it in. Do you have any issue with that?

**Comment by keithlayne** [comment]
This is what I found:

```diff
diff --git a/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml b/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
index 7b47e384..6f00a8fa 100644
--- a/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
+++ b/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml
@@ -218,7 +218,7 @@ spec:
       - topologyKey: {{ .Values.prometheus.prometheusSpec.podAntiAffinityTopologyKey }}
         labelSelector:
           matchExpressions:
-            - {key: app, operator: In, values: [prometheus]}
+            - {key: app.kubernetes.io/name, operator: In, values: [prometheus]}
             - {key: prometheus, operator: In, values: [{{ template "kube-prometheus-stack.fullname" . }}-prometheus]}
 {{- else if eq .Values.prometheus.prometheusSpec.podAntiAffinity "soft" }}
     podAntiAffinity:
@@ -228,7 +228,7 @@ spec:
           topologyKey: {{ .Values.prometheus.prometheusSpec.podAntiAffinityTopologyKey }}
           labelSelector:
             matchExpressions:
-              - {key: app, operator: In, values: [prometheus]}
+              - {key: app.kubernetes.io/name, operator: In, values: [prometheus]}
               - {key: prometheus, operator: In, values: [{{ template "kube-prometheus-stack.fullname" . }}-prometheus]}
 {{- end }}
 {{- end }}
 ```
 
 An extra set of eyeballs is welcome.

**Comment by laverya** [comment]
That matches what I found! https://github.com/prometheus-community/helm-charts/blob/429987f/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L221 & https://github.com/prometheus-community/helm-charts/blob/429987f/charts/kube-prometheus-stack/templates/prometheus/prometheus.yaml#L231

**Pull request merged**
