### PR TITLE
migrate minio to rook even if it is HA

### PR DESCRIPTION
**Pull request by laverya**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note
Fix an issue where HA MinIO deployments would not be migrated to Rook's object store.
```

### CODE REVIEW

**Comment by emosbaugh** [comment]
Does this need a release note?

**Comment by laverya** [comment]
Why would it not?

**Comment by emosbaugh** [comment]
> Why would it not?

Oh sorry. I didn't see it in the mobile app. I see there is one.

**Review by emosbaugh — APPROVED** [review]

**Comment by laverya** [comment]
> > Why would it not?
> 
> Oh sorry. I didn't see it in the mobile app. I see there is one.

Ahhh gotcha, I thought you were asking why I had included one 😅

**Pull request merged**
