### PR TITLE
added cert-manager 1.0.3

### PR DESCRIPTION
**Pull request by nikogura**
I attempted to follow the instructions here: https://kurl.sh/docs/add-on-author/

Apologies in advance if I missed something.

I left the cert-manager.yaml in one big file because that's how the cert-manager project publishes it: https://github.com/jetstack/cert-manager/releases/download/v1.0.3/cert-manager.yaml.

Let me know if you'd like it broken apart.

### CODE REVIEW

**Comment by jesserobbins** [comment]
@grantmiller note that you have a configuration error in your cla-generator. You need to expand it to allow for CCLAs with individual contributor authorizations to avoid us having to provide this kind of note. Orion Labs, Inc. authorizes @nikogura

**Comment by jesserobbins** [comment]
@grantmiller just wanted to note that you have a configuration error in your cla-generator configuration. You need to expand it to allow for CCLAs with individual contributor authorizations to avoid us having to provide this kind of note. ;-) In this case,  Orion Labs, Inc. is authorizing its employee @nikogura to make the contribution contained in this specific pull request and to agree to the CLA for this commit. I have also signed the CLA for this commit.

**Comment by laverya** [comment]
I like it! Let me bring this to the rest of the team

**Review by laverya — APPROVED** [review]
We'll need to add references to this elsewhere - make it so that it shows up and is included in the yaml spec etc
but that can be a different PR

**Review by areed — APPROVED** [review]

**Pull request merged**
