### PR TITLE
chore: standardize logging and example

### PR DESCRIPTION
**Pull request by emosbaugh**
#### What this PR does / why we need it:

This change proposes a standard for logging in the kurl cli. It tries to disambiguate between logging and command output. It does not change behavior, as log statements will continue to go to stderr with timestamps. Additionally it adds a debug logger for verbose output.

### CODE REVIEW

**Review by ricardomaraschini — APPROVED** [review]
I liked it a lot.

**Review by rrpolanco — APPROVED** [review]
This was worthwhile refactor 👍

**Comment by laverya** [comment]
Could we see some before+after log line examples?
Or is this not intended to change output?

**Comment by emosbaugh** [comment]
> Could we see some before+after log line examples? Or is this not intended to change output?

There should be no change. The logger is instantiated the same as the log.DefaultLogger and includes timestamps.

**Review by camilamacedo86 — APPROVED** [review]

**Review by camilamacedo86 — APPROVED** [review]

**Pull request merged**
