### PR TITLE
Automated Antrea version update 1.10.0

### PR DESCRIPTION
**Pull request by replicated-ci-kurl**
Automated changes by the [cron-antrea-update](https://github.com/replicatedhq/kURL/blob/main/.github/workflows/update-antrea.yaml) GitHub action

```release-note
Adds [Antrea add-on](https://kurl.sh/docs/add-ons/antrea) version 1.10.0.
```

### CODE REVIEW

**Comment by rrpolanco** [comment]
Non-Ubuntu OS tests are failing with the following error:
```
modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.18.0-305.3.1.el8.x86_64
Antrea with inter-node encryption enabled requires the wireguard kernel module be available. https://www.wireguard.com/install/
```

**Comment by emosbaugh** [comment]
> Non-Ubuntu OS tests are failing with the following error:
> 
> ```
> modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.18.0-305.3.1.el8.x86_64
> Antrea with inter-node encryption enabled requires the wireguard kernel module be available. https://www.wireguard.com/install/
> ```

Can we either set [isEncryptionDisabled: true](https://kurl.sh/docs/add-ons/antrea) or install wireguard in [preinit](https://github.com/replicatedhq/kURL/blob/239eadd1460a871d0e4669d3e62247b2fe237d00/testgrid/specs/os-full.yaml#L45-L48) or [runcmd.sh](https://github.com/replicatedhq/kURL/blob/main/testgrid/tgrun/pkg/runner/vmi/embed/runcmd.sh)?

**Comment by rrpolanco** [comment]
Need to investigate and fix failing tests.

**Comment by rrpolanco** [comment]
Test is failing with the following error:
```bash
[Host OS Info] Running collector...
2022-09-14 05:11:40+00:00 [PASS] Number of CPUs: This server has at least 4 CPU cores
2022-09-14 05:11:40+00:00 [PASS] Amount of Memory: The system has at least 8G of memory
2022-09-14 05:11:40+00:00 [PASS] Ephemeral Disk Usage /var/lib/kubelet: The disk containing directory /var/lib/kubelet has at least 30Gi of total space, has at least 10Gi of disk space available, and is less than 60% full
2022-09-14 05:11:40+00:00 [PASS] Kubernetes API TCP Port Status: Port 6443 is open
2022-09-14 05:11:40+00:00 [PASS] ETCD Client API TCP Port Status: Port 2379 is open
2022-09-14 05:11:40+00:00 [PASS] ETCD Server API TCP Port Status: Port 2380 is open
2022-09-14 05:11:40+00:00 [PASS] ETCD Health Server TCP Port Status: Port 2381 is available
2022-09-14 05:11:40+00:00 [PASS] Kubelet Health Server TCP Port Status: Port 10248 is available
2022-09-14 05:11:40+00:00 [PASS] Kubelet API TCP Port Status: Port 10250 is open
2022-09-14 05:11:40+00:00 [PASS] Kube Controller Manager Health Server TCP Port Status: Port 10257 is available
2022-09-14 05:11:40+00:00 [PASS] Kube Scheduler Health Server TCP Port Status: Port 10259 is available
2022-09-14 05:11:40+00:00 [PASS] Filesystem Performance: Write latency is ok (p99 target < 10ms, actual: 4.835118ms)
2022-09-14 05:11:40+00:00 [PASS] NTP Status: System clock is synchronized
2022-09-14 05:11:40+00:00 [PASS] NTP Status: Timezone is set to UTC
2022-09-14 05:11:40+00:00 [PASS] Ephemeral Disk Usage /opt/replicated/rook: The disk containing directory /opt/replicated/rook has at least 25Gi of disk space available and is less than 80% full
2022-09-14 05:11:40+00:00 [PASS] Can Access Replicated API: Connected to https://replicated.app
⚙  Host preflights success
modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.18.0-305.3.1.el8.x86_64
Antrea with inter-node encryption enabled requires the wireguard kernel module be available. https://www.wireguard.com/install/
+ KURL_EXIT_STATUS=1
```

The Antrea add-on test needs to be changed so the wireguard kernel module is enabled as a preInstall step.

**Comment by rrpolanco** [comment]
All addon tests fail except on Debian (Ubuntu).  The test failures stem from the kernel not having the `wireguard` module.

```bash
⚙  Host preflights success
modprobe: FATAL: Module wireguard not found in directory /lib/modules/4.18.0-305.3.1.el8.x86_64
Antrea with inter-node encryption enabled requires the wireguard kernel module be available. https://www.wireguard.com/install/
+ KURL_EXIT_STATUS=1
```

To get the tests working again, we need to:
1. Change the Antrea tests so that encryption is disabled (i.e. `isEncryptionDisabled: true`).
2. Patch the kernel on Centos, Oracle-Linux, Amazon-Linux so that we can test Antrea with encryption enabled (i.e. wireguard kernel module loaded).

**Comment by camilamacedo86** [comment]
Closing this one since we are moving away in afavor of flannel.

**Comment by camilamacedo86** [comment]
we are moving to flannel instead.

**Pull request closed without merging**
