### PR TITLE
Automated Prometheus version update 0.59.1-40.1.0

### PR DESCRIPTION
**Pull request by replicated-ci-kurl**
Automated changes by the [cron-prometheus-update](https://github.com/replicatedhq/kURL/blob/main/.github/workflows/update-prometheus.yaml) GitHub action

```release-note
  Adds [Prometheus add-on](https://kurl.sh/docs/add-ons/prometheus) version 0.59.1-40.1.0.
```

### CODE REVIEW

**Comment by laverya** [comment]
I would prefer NOT to merge this as it's just a helm chart change: `0.58.0-39.13.3` is still using operator `0.58.0` after all.

We should change the automation at some point.

**Comment by emosbaugh** [comment]
Agreed. There is very little of substance here

```
$ diff -r 0.58.0-39.12.1 0.58.0-39.13.3 | grep -E '^[><]' |  grep -v ' chart: ' | grep -v ' release: ' | grep -v 'app.kubernetes.io/' | grep -v 'helm.sh/chart' | grep -v 'jobLabel' | grep -v 'checksum/config'
<     local src="$DIR/addons/prometheus/0.58.0-39.12.1"
>     local src="$DIR/addons/prometheus/0.58.0-39.13.3"
<         checksum/sc-dashboard-provider-config: 2ece7d2111c9f00b6dee12efae1174f9e72fb6e4f0cde72d1a040b09e5ecd8a5
>         checksum/sc-dashboard-provider-config: bb3cb565c799e56da07e9643b290b81811ce6ea973ab04714729a72716dccbc5
<             - name: LOG_LEVEL
<               value: "INFO"
>   walCompression: false
> 
```

**Comment by laverya** [comment]
We should have that diff be run automatically and presented as part of the PR IMO @emosbaugh 
For all the automated PRs

**Comment by laverya** [comment]
Manifest diff:
```
diff 0.58.0-39.12.1 0.59.1-40.1.0
diff 0.58.0-39.12.1/Manifest 0.59.1-40.1.0/Manifest
4c4
< image kube-state-metrics registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.5.0
---
> image kube-state-metrics registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.6.0
6c6
< image prometheus quay.io/prometheus/prometheus:v2.37.0
---
> image prometheus quay.io/prometheus/prometheus:v2.38.0
8,9c8,9
< image prometheus-config-reloader quay.io/prometheus-operator/prometheus-config-reloader:v0.58.0
< image prometheus-operator quay.io/prometheus-operator/prometheus-operator:v0.58.0
---
> image prometheus-config-reloader quay.io/prometheus-operator/prometheus-config-reloader:v0.59.1
> image prometheus-operator quay.io/prometheus-operator/prometheus-operator:v0.59.1
Common subdirectories: 0.58.0-39.12.1/crds and 0.59.1-40.1.0/crds
diff 0.58.0-39.12.1/install.sh 0.59.1-40.1.0/install.sh
4c4
<     local src="$DIR/addons/prometheus/0.58.0-39.12.1"
---
>     local src="$DIR/addons/prometheus/0.59.1-40.1.0"
Common subdirectories: 0.58.0-39.12.1/operator and 0.59.1-40.1.0/operator
```

**Pull request closed without merging**
