### PR TITLE
Automated MinIO version update RELEASE.2022-12-12T19-27-27Z

### PR DESCRIPTION
**Pull request by replicated-ci-kurl**
Automated changes by the [cron-minio-update](https://github.com/replicatedhq/kURL/blob/main/.github/workflows/update-minio.yaml) GitHub action

```release-note
Adds [MinIO add-on](https://kurl.sh/docs/add-ons/minio) version RELEASE.2022-12-12T19-27-27Z.
```

### CODE REVIEW

**Comment by laverya** [comment]
This would be closed by https://github.com/replicatedhq/kURL/pull/3603

**Review by emosbaugh — APPROVED** [review]
Testgrid passing

**Review by emosbaugh — CHANGES_REQUESTED** [review]
testing

**Comment by ricardomaraschini** [comment]
@emosbaugh any last comment before I merge this ? Testgrid is green (with exception of that longhorn issue).

**Comment by emosbaugh** [comment]
@ricardomaraschini lgtm. thanks

**Comment by ricardomaraschini** [comment]
@emosbaugh I think we can't merge this because you have requested for changes :-(

**Review by emosbaugh — APPROVED** [review]

**Comment by emosbaugh** [comment]
> @emosbaugh I think we can't merge this because you have requested for changes :-(

approved

**Pull request merged**
