### PR TITLE
More host preflights

### PR DESCRIPTION
**Pull request by areed**

### CODE REVIEW

**Review by emosbaugh — COMMENTED** [review]
I was trying to avoid not writing valid yaml because that is what we expect of all other kots.io documents but I can see how that may be a problem

**Comment by areed** [comment]
> I was trying to avoid not writing valid yaml because that is what we expect of all other kots.io documents but I can see how that may be a problem

I don't follow. Which kots.io documents have to be valid yaml?

**Comment by emosbaugh** [comment]
All. Because otherwise we can't lint them

**Review by emosbaugh — APPROVED** [review]
The host preflight tool is starting to feel a little cumbersome with all these additional args. Lets keep going with it as is for now but it may be worth revisiting at some point.

**Comment by emosbaugh** [comment]
Testgrid is still running

**Pull request merged**
