### PR TITLE
Fix openebs automation. Revert hardcoding images.

### PR DESCRIPTION
**Pull request by emosbaugh**
#### What this PR does / why we need it:

Fixes failed automated pr https://github.com/replicatedhq/kURL/pull/3415

Reverts https://github.com/replicatedhq/kURL/commit/ee07932e3352547907a94ad340ca1ad4297a5340

Fixed upstream https://github.com/openebs/charts/pull/310

### CODE REVIEW

**Review by laverya — APPROVED** [review]

**Comment by laverya** [comment]
Will this fix the missing name too?

**Comment by emosbaugh** [comment]
> Will this fix the missing name too?

I'm not sure what you are referring to

**Comment by laverya** [comment]
> >Will this fix the missing name too?
> 
> I'm not sure what you are referring to



Screen Shot 2022-09-12 at 20 36 20
Missing version. I meant missing version. 🤦

**Comment by emosbaugh** [comment]
> > > Will this fix the missing name too?
> > 
> > 
> > I'm not sure what you are referring to
> 
> Screen Shot 2022-09-12 at 20 36 20
> 
> Missing version. I meant missing version. 🤦

no. i missed that. will fix in a follow up pr

**Pull request merged**
