### PR TITLE
Upgrading Weave add-on version to 2.7.0

### PR DESCRIPTION
**Pull request by paha**
RE: https://github.com/weaveworks/weave/releases

Adding missing params for weave-npc pod
`dnsPolicy: ClusterFirstWithHostNet`
and
`priorityClassName: system-node-critical`

### CODE REVIEW

**Review by areed — COMMENTED** [review]
I see in the weave yaml it sets `dnsPolicy: ClusterFirstWithHostNet` and `priorityClassName: system-node-critical`. Should we include those in ours?

**Review by areed — APPROVED** [review]
LGTM. I'd wait to merge until after the release.

**Comment by paha** [comment]
@areed thanks.
Yes, both should be present. Overall Weave CNI functionality should not be impacted by them, so it might be optional for us to update the previous versions. What do you think?

**Comment by areed** [comment]
Agreed, no need to risk updating previous versions.

**Pull request merged**
