### PR TITLE
Automated Containerd version update 1.4.4

### PR DESCRIPTION
**Pull request by replicatedbot**
Automated changes by the [cron-containerd-update](https://github.com/replicatedhq/kURL/blob/master/.github/workflows/update-containerd.yaml) GitHub action

### CODE REVIEW

**Comment by laverya** [comment]
https://github.com/replicatedhq/kURL/commit/f992b258ebb00e4c195a6cddd39cd60faa3bd92a

I think we need to update the template

**Comment by emosbaugh** [comment]
@laverya #1407 (cc @MikaelSmith for next time)

**Comment by MikaelSmith** [comment]
So it should go at https://github.com/replicatedhq/kURL/blob/master/addons/containerd/template/base/install.sh#L39 instead?

**Comment by emosbaugh** [comment]
We are working towards automating all add-on updates. They do not regenerate older versions so I would suggest adding it there as well as where you did.

**Comment by emosbaugh** [comment]
Closing this. Will regenerate.

**Pull request closed without merging**
